name: workflow comandos
 
on: [push]
 
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: crear la carpeta de trabajo
              run: 
                    pwd
                    cd /home/runner/work/Anchart-Adm.-Sist.-y-Redes/Anchart-Adm.-Sist.-y-Redes/
                    mkdir carpeta
                    cd /home/runner/work/Anchart-Adm.-Sist.-y-Redes/Anchart-Adm.-Sist.-y-Redes/carpeta/
  
                    
                    