name: mi primer workflow
 
on: [push]
 
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: echo a string
              run: |
                    echo "Hello World"
                    cd /home/runner/work/Anchart-Adm.-Sist.-y-Redes/.github/workflows/
                    cp workflow.yml /home/runner/work/Anchart-Adm.-Sist.-y-Redes/workflow-copia.yml
                    ls /home/runner/work/Anchart-Adm.-Sist.-y-Redes
                    cd /home/runner/work/Anchart-Adm.-Sist.-y-Redes
                    pwd